language: julia
os:
    - linux
    - osx
julia:
    - release
    - nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone("https://github.com/JuliaQuantum/QuBase.jl.git")';
    - julia -e 'Pkg.clone("https://github.com/marcusps/ExpmV.jl.git")';
    - julia -e 'Pkg.clone("https://github.com/acroy/Expokit.jl.git")';
    - julia -e 'Pkg.clone(pwd()); Pkg.build("QuDynamics"); Pkg.test("QuDynamics")';
    - julia --code-coverage=user -e 'include("test/runtests.jl")';
after_success:
    - julia -e 'cd(Pkg.dir("QuDynamics")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
matrix:
  allow_failures: # import normalize in QuBase as this is in Base in v 0.5.
    - julia: nightly
  fast_finish: true
