language: julia
os:
    - linux
    - osx
julia:
    - release
    - nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone("https://github.com/JuliaQuantum/QuBase.jl.git")';
    - julia -e 'Pkg.clone(pwd()); Pkg.build("QuDynamics"); Pkg.checkout("ODE"); Pkg.test("QuDynamics")';
